default: &default
  adapter: mysql2
  pool: 5
  timeout: 5000
  host: <%= ENV['VPN_GATE_DB_HOST'] || 'localhost'%>
  port: <%= ENV['VPN_GATE_DB_PORT'] || '3306'%>
  username: <%= ENV['VPN_GATE_DB_USER'] || 'vpn_gate'%>
  password: <%= ENV['VPN_GATE_DB_PASSWORD'] || 'password' %>


development:
  <<: *default
  database: vpn_gate_dev
  username: vpn_gate_dev
  properties:
    useSSL: false

test:
  <<: *default
  database: vpn_gate_test
  username: vpn_gate_test
  properties:
    useSSL: false

production:
  <<: *default
  database: <%= ENV['VPN_GATE_DB_NAME'] %>

